### ISSUE TITLE
add basic homepage for the project

### ISSUE THREAD

**Issue by malloxpb** [masspvn/massp-webapp#5]
Currently, the webapp does not have a homepage yet (it only has the "HELLO RAILS" header)

I was thinking of using some of the templates on [html5up](https://html5up.net/), particularly [this theme](https://html5up.net/dopetrope) (@tramvn1996 and I chose this). HTML5up is kinda okay with everybody using their theme, as long as we cite the source at the end of the website (something like "designed by html5up". Their license can be found [here](https://html5up.net/license)

What's your thought @chauvm ? 😄

**Comment by chauvm** [comment]
Looks good 👍

**Comment by malloxpb** [comment]
resolved in #8
